### ISSUE TITLE
Can't find zlib.h

### ISSUE THREAD

**Issue by nigelhorne** [benkasminbullock/gzip-faster#5]
Compiles fail with

Can't link/include C library 'zlib.h', 'z', aborting

But it exists:

-rw-r--r-- 1 root root 87883 Nov 27  2014 /usr/include/zlib.h

And I have the zlib1g-dev package installed.  Do I need something else?

**Comment by benkasminbullock** [comment]
Please follow these steps:

    wget https://cpan.metacpan.org/authors/id/B/BK/BKB/Gzip-Faster-0.13_01.tar.gz
    tar xfz Gzip-Faster-0.13_01.tar.gz
    cd Gzip-Faster-0.13_01
    perl check-zlib.pl > check.txt 2>&1

At the end of this, you should get a file "check.txt". Can you either email the file to me at bkb@cpan.org or copy and paste it here? Thanks.

**Comment by nigelhorne** [comment]
hornenj@ncbimac2027:~/.cpan/build/Gzip-Faster-0.13-fSYISA$ perl Makefile.PL  
Can't link/include C library 'zlib.h', 'z', aborting.
hornenj@ncbimac2027:~/.cpan/build/Gzip-Faster-0.13-fSYISA$ 

check-libz.pl:23: --------------------------------------------------
check-libz.pl:25: Your system info: Linux cyberpower2 4.2.0-1-amd64 #1 SMP Debian 4.2.5-1 (2015-10-27) x86_64
check-libz.pl:26: --------------------------------------------------
check-libz.pl:27: I will try to locate libz on your computer.
check-libz.pl:28: I am now running Devel::CheckLib to find libz.
check-libz.pl:29: The following is the output from Devel::CheckLib.
check-libz.pl:30: --------------------------------------------------
# /home/njh/perl5/perlbrew/bin/ gcc-5 -D_REENTRANT -D_GNU_SOURCE -O2 -mtune=native -march=native -Wall -pipe -ftree-vectorize -fdiagnostics-color=auto -fsanitize=bounds -g -fwrapv -fno-strict-aliasing -fstack-protector-strong -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -fsanitize=bounds -g -fstack-protector-strong -L/usr/local/lib assertlibcH_VHpDx.c -o assertlibcw2uEzQX
# /home/njh/perl5/perlbrew/bin/ gcc-5 -D_REENTRANT -D_GNU_SOURCE -O2 -mtune=native -march=native -Wall -pipe -ftree-vectorize -fdiagnostics-color=auto -fsanitize=bounds -g -fwrapv -fno-strict-aliasing -fstack-protector-strong -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -fsanitize=bounds -g -fstack-protector-strong -L/usr/local/lib assertlibOxHlFv_g.c -o assertlibNroAiJbs -lz
check-libz.pl:32: --------------------------------------------------
check-libz.pl:40: libz could not be found by Devel::CheckLib.
njh@cyberpower2:/tmp/Gzip-Faster-0.13_01$ ls -l /usr/include/zlib.h 
-rw-r--r-- 1 root root 87883 Nov 27  2014 /usr/include/zlib.h
njh@cyberpower2:/tmp/Gzip-Faster-0.13_01$

**Comment by benkasminbullock** [comment]
(sorry to edit your comment, just added <pre> tags around it.)

OK there is an error there, it seems to be an error in Devel::CheckLib. It's got your compiler as

/home/njh/perl5/perlbrew/bin/

then after that there is a space, and then gcc-5. That clearly isn't going to work. 

Looking at Devel::CheckLib the source code is Perl golf/obfuscated/something and it doesn't have any option to turn on better debugging than what we have above. I tried to edit it but it is just a mess with no comments and golf everywhere, so what I have done is just to remove Devel::CheckLib from the distribution, can you try the CPAN version again? Here is the download link:

https://cpan.metacpan.org/authors/id/B/BK/BKB/Gzip-Faster-0.13_02.tar.gz

Maybe it will just install.

**Comment by nigelhorne** [comment]
Thanks for your quick response. I've only tried the new version on one host and one configuration so far, but on that configuration it's now working better.

**Comment by benkasminbullock** [comment]
I'll close this issue now I think. Please let me know if there are any more problems.
